services:
# =====================================================================================
# ENV DEV
# =====================================================================================

  user_role-service-dev:
    image: user_role-service-dev
    container_name: user_role-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "pnpm exec prisma migrate deploy && pnpm exec prisma generate && pnpm run start:dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@user_role-db-dev:5432/user_role-db
    env_file:
      - .env
    depends_on:
      - user_role-db-dev
    profiles: ["dev"]

  user_role-db-dev:
    image: postgres:16
    container_name: user_role-db-dev
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    profiles: ["dev"]


# =====================================================================================
# ENV PROD
# =====================================================================================

  user_role-service-prod:
    container_name: user_role-service-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - ./src/infrastructure/config/.env.prod
    depends_on:
      - user_role-db-prod
    restart: unless-stopped
    profiles: ["prod"]

  user_role-db-prod:
    image: postgres:16
    container_name: user_role-db-prod
    env_file:
      - ./src/infrastructure/config/.env.prod
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["prod"]

volumes:
  pgdata-dev:
  pgdata-prod:
