export const CodesError = {
  // Common
  PUBLIC_ID_INVALID: 'PUBLIC_ID_INVALID',
  USER_ID_INVALID: 'USER_ID_INVALID',

  // roles_table
  ROLE_NAME_INVALID: 'ROLE_NAME_INVALID',
  ROLE_DESCRIPTION_INVALID: 'ROLE_DESCRIPTION_INVALID',
  ROLE_IS_SYSTEM_INVALID: 'ROLE_IS_SYSTEM_INVALID',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_ALREADY_EXISTS: 'ROLE_NAME_ALREADY_EXISTS',

  // permissions_table
  PERMISSION_NAME_INVALID: 'PERMISSION_NAME_INVALID',
  PERMISSION_DESCRIPTION_INVALID: 'PERMISSION_DESCRIPTION_INVALID',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PERMISSION_NAME_ALREADY_EXISTS: 'PERMISSION_NAME_ALREADY_EXISTS',

  // user_roles_table
  USER_ROLE_NOT_FOUND: 'USER_ROLE_NOT_FOUND',
  USER_ROLE_ALREADY_EXISTS: 'USER_ROLE_ALREADY_EXISTS',

  // role_permissions_table
  ROLE_PERMISSION_NOT_FOUND: 'ROLE_PERMISSION_NOT_FOUND',
  ROLE_PERMISSION_ALREADY_EXISTS: 'ROLE_PERMISSION_ALREADY_EXISTS',

  // permission_overrides_table
  PERMISSION_OVERRIDE_NOT_FOUND: 'PERMISSION_OVERRIDE_NOT_FOUND',
  PERMISSION_OVERRIDE_ALREADY_EXISTS: 'PERMISSION_OVERRIDE_ALREADY_EXISTS',
  MODE_INVALID: 'MODE_INVALID',
  NOTE_INVALID: 'NOTE_INVALID',

  // Backward compatibility with existing validators
  NAME_INVALID: 'NAME_INVALID',
  DESCRIPTION_INVALID: 'DESCRIPTION_INVALID',
  ISSYSTEM_INVALID: 'ISSYSTEM_INVALID',
} as const;

export type CodesError = typeof CodesError[keyof typeof CodesError];
