// src/application/errors/codes.error.ts

export const CodesError = {
  DATA_INVALID: 'DATA_INVALID',
  PUBLIC_ID_INVALID: 'PUBLIC_ID_INVALID',
  USER_ID_INVALID: 'USER_ID_INVALID',

  // roles_table
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_ALREADY_EXISTS: 'ROLE_NAME_ALREADY_EXISTS',

  // permissions_table
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PERMISSION_NAME_ALREADY_EXISTS: 'PERMISSION_NAME_ALREADY_EXISTS',

  // user_roles_table
  USER_ROLE_NOT_FOUND: 'USER_ROLE_NOT_FOUND',
  USER_ROLE_ALREADY_EXISTS: 'USER_ROLE_ALREADY_EXISTS',

  // role_permissions_table
  ROLE_PERMISSION_NOT_FOUND: 'ROLE_PERMISSION_NOT_FOUND',
  ROLE_PERMISSION_ALREADY_EXISTS: 'ROLE_PERMISSION_ALREADY_EXISTS',

  // permission_overrides_table
  PERMISSION_OVERRIDE_NOT_FOUND: 'PERMISSION_OVERRIDE_NOT_FOUND',
  PERMISSION_OVERRIDE_ALREADY_EXISTS: 'PERMISSION_OVERRIDE_ALREADY_EXISTS',
} as const;

export type CodesError = typeof CodesError[keyof typeof CodesError];
